// Copyright (c) 2023 Sam Blenny
// SPDX-License-Identifier: MIT
//
// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MAKE EDITS HERE
// See codegen.py for details
//
#include "mkb_autogen.h"

// Markab VM opcode dictionary
const char * const mk_opcodes[MK_OPCODES_LEN] = {
	"NOP",     //  0
	"RESET",   //  1
	"JMP",     //  2
	"JAL",     //  3
	"RET",     //  4
	"BZ",      //  5
	"BFOR",    //  6
	"U8",      //  7
	"U16",     //  8
	"I32",     //  9
	"HALT",    // 10
	"TRON",    // 11
	"TROFF",   // 12
	"IODUMP",  // 13
	"IOKEY",   // 14
	"IORH",    // 15
	"IOLOAD",  // 16
	"FOPEN",   // 17
	"FREAD",   // 18
	"FWRITE",  // 19
	"FSEEK",   // 20
	"FTELL",   // 21
	"FTRUNC",  // 22
	"FCLOSE",  // 23
	"MTR",     // 24
	"R",       // 25
	"CALL",    // 26
	"PC",      // 27
	"MTE",     // 28
	"LB",      // 29
	"SB",      // 30
	"LH",      // 31
	"SH",      // 32
	"LW",      // 33
	"SW",      // 34
	"ADD",     // 35
	"SUB",     // 36
	"MUL",     // 37
	"DIV",     // 38
	"MOD",     // 39
	"SLL",     // 40
	"SRL",     // 41
	"SRA",     // 42
	"INV",     // 43
	"XOR",     // 44
	"OR",      // 45
	"AND",     // 46
	"GT",      // 47
	"LT",      // 48
	"EQ",      // 49
	"NE",      // 50
	"ZE",      // 51
	"INC",     // 52
	"DEC",     // 53
	"IOEMIT",  // 54
	"IODOT",   // 55
	"IODH",    // 56
	"IOD",     // 57
	"RDROP",   // 58
	"DROP",    // 59
	"DUP",     // 60
	"OVER",    // 61
	"SWAP",    // 62
	"MTA",     // 63
	"LBA",     // 64
	"LBAI",    // 65
	"AINC",    // 66
	"ADEC",    // 67
	"A",       // 68
	"MTB",     // 69
	"LBB",     // 70
	"LBBI",    // 71
	"SBBI",    // 72
	"BINC",    // 73
	"BDEC",    // 74
	"B",       // 75
	"TRUE",    // 76
	"FALSE",   // 77
};

// Markab language core vocabulary
const mk_voc_item_t mk_core_voc[MK_CORE_VOC_LEN] = {
	{ {"Heap"},        MK_T_CONST, 0x0000    },
	{ {"HeapRes"},     MK_T_CONST, 0xE000    },
	{ {"HeapMax"},     MK_T_CONST, 0xE0FF    },
	{ {"DP"},          MK_T_CONST, 0xE100    },
	{ {"IN"},          MK_T_CONST, 0xE104    },
	{ {"CORE_V"},      MK_T_CONST, 0xE108    },
	{ {"EXT_V"},       MK_T_CONST, 0xE10C    },
	{ {"MODE"},        MK_T_CONST, 0xE110    },
	{ {"LASTCALL"},    MK_T_CONST, 0xE118    },
	{ {"NEST"},        MK_T_CONST, 0xE11C    },
	{ {"BASE"},        MK_T_CONST, 0xE120    },
	{ {"EOF"},         MK_T_CONST, 0xE124    },
	{ {"LASTWORD"},    MK_T_CONST, 0xE128    },
	{ {"IRQRX"},       MK_T_CONST, 0xE12C    },
	{ {"OK_EN"},       MK_T_CONST, 0xE130    },
	{ {"LOADNEST"},    MK_T_CONST, 0xE134    },
	{ {"IRQERR"},      MK_T_CONST, 0xE138    },
	{ {"IB"},          MK_T_CONST, 0xE200    },
	{ {"Pad"},         MK_T_CONST, 0xE300    },
	{ {"Scratch"},     MK_T_CONST, 0xE400    },
	{ {"MemMax"},      MK_T_CONST, 0xFFFF    },
	{ {"T_VAR"},       MK_T_CONST, 0         },
	{ {"T_CONST"},     MK_T_CONST, 1         },
	{ {"T_OP"},        MK_T_CONST, 2         },
	{ {"T_OBJ"},       MK_T_CONST, 3         },
	{ {"T_IMM"},       MK_T_CONST, 4         },
	{ {"MODE_INT"},    MK_T_CONST, 0         },
	{ {"MODE_COM"},    MK_T_CONST, 1         },
	{ {"ErrUnknown"},  MK_T_CONST, 11        },
	{ {"ErrNest"},     MK_T_CONST, 12        },
	{ {"ErrFilepath"}, MK_T_CONST, 9         },
	{ {"HashA"},       MK_T_CONST, 7         },
	{ {"HashB"},       MK_T_CONST, 8         },
	{ {"HashC"},       MK_T_CONST, 38335     },
	{ {"HashBins"},    MK_T_CONST, 64        },
	{ {"HashMask"},    MK_T_CONST, 63        },
	{ {"nop"},         MK_T_OP,    MK_NOP    },
	{ {"reset"},       MK_T_OP,    MK_RESET  },
	{ {"halt"},        MK_T_OP,    MK_HALT   },
	{ {"tron"},        MK_T_OP,    MK_TRON   },
	{ {"troff"},       MK_T_OP,    MK_TROFF  },
	{ {"dump"},        MK_T_OP,    MK_IODUMP },
	{ {"key"},         MK_T_OP,    MK_IOKEY  },
	{ {"iorh"},        MK_T_OP,    MK_IORH   },
	{ {"load_"},       MK_T_OP,    MK_IOLOAD },
	{ {"fopen_"},      MK_T_OP,    MK_FOPEN  },
	{ {"fread"},       MK_T_OP,    MK_FREAD  },
	{ {"fwrite"},      MK_T_OP,    MK_FWRITE },
	{ {"fseek"},       MK_T_OP,    MK_FSEEK  },
	{ {"ftell"},       MK_T_OP,    MK_FTELL  },
	{ {"ftrunc"},      MK_T_OP,    MK_FTRUNC },
	{ {"fclose"},      MK_T_OP,    MK_FCLOSE },
	{ {">r"},          MK_T_OP,    MK_MTR    },
	{ {"r"},           MK_T_OP,    MK_R      },
	{ {"call"},        MK_T_OP,    MK_CALL   },
	{ {"pc"},          MK_T_OP,    MK_PC     },
	{ {">err"},        MK_T_OP,    MK_MTE    },
	{ {"@"},           MK_T_OP,    MK_LB     },
	{ {"!"},           MK_T_OP,    MK_SB     },
	{ {"h@"},          MK_T_OP,    MK_LH     },
	{ {"h!"},          MK_T_OP,    MK_SH     },
	{ {"w@"},          MK_T_OP,    MK_LW     },
	{ {"w!"},          MK_T_OP,    MK_SW     },
	{ {"+"},           MK_T_OP,    MK_ADD    },
	{ {"-"},           MK_T_OP,    MK_SUB    },
	{ {"*"},           MK_T_OP,    MK_MUL    },
	{ {"/"},           MK_T_OP,    MK_DIV    },
	{ {"%"},           MK_T_OP,    MK_MOD    },
	{ {"<<"},          MK_T_OP,    MK_SLL    },
	{ {">>"},          MK_T_OP,    MK_SRL    },
	{ {">>>"},         MK_T_OP,    MK_SRA    },
	{ {"inv"},         MK_T_OP,    MK_INV    },
	{ {"xor"},         MK_T_OP,    MK_XOR    },
	{ {"or"},          MK_T_OP,    MK_OR     },
	{ {"and"},         MK_T_OP,    MK_AND    },
	{ {">"},           MK_T_OP,    MK_GT     },
	{ {"<"},           MK_T_OP,    MK_LT     },
	{ {"="},           MK_T_OP,    MK_EQ     },
	{ {"!="},          MK_T_OP,    MK_NE     },
	{ {"0="},          MK_T_OP,    MK_ZE     },
	{ {"1+"},          MK_T_OP,    MK_INC    },
	{ {"1-"},          MK_T_OP,    MK_DEC    },
	{ {"emit"},        MK_T_OP,    MK_IOEMIT },
	{ {"."},           MK_T_OP,    MK_IODOT  },
	{ {"iodh"},        MK_T_OP,    MK_IODH   },
	{ {"iod"},         MK_T_OP,    MK_IOD    },
	{ {"rdrop"},       MK_T_OP,    MK_RDROP  },
	{ {"drop"},        MK_T_OP,    MK_DROP   },
	{ {"dup"},         MK_T_OP,    MK_DUP    },
	{ {"over"},        MK_T_OP,    MK_OVER   },
	{ {"swap"},        MK_T_OP,    MK_SWAP   },
	{ {">a"},          MK_T_OP,    MK_MTA    },
	{ {"@a"},          MK_T_OP,    MK_LBA    },
	{ {"@a+"},         MK_T_OP,    MK_LBAI   },
	{ {"a+"},          MK_T_OP,    MK_AINC   },
	{ {"a-"},          MK_T_OP,    MK_ADEC   },
	{ {"a"},           MK_T_OP,    MK_A      },
	{ {">b"},          MK_T_OP,    MK_MTB    },
	{ {"@b"},          MK_T_OP,    MK_LBB    },
	{ {"@b+"},         MK_T_OP,    MK_LBBI   },
	{ {"!b+"},         MK_T_OP,    MK_SBBI   },
	{ {"b+"},          MK_T_OP,    MK_BINC   },
	{ {"b-"},          MK_T_OP,    MK_BDEC   },
	{ {"b"},           MK_T_OP,    MK_B      },
	{ {"true"},        MK_T_OP,    MK_TRUE   },
	{ {"false"},       MK_T_OP,    MK_FALSE  },
};
