# Copyright (c) 2023 Sam Blenny
# SPDX-License-Identifier: MIT
#
# This is a plan 9 mkfile for use with mk.
# Usage examples:
#   term% mk
#   term% mk clean
#
</$objtype/mkfile

AUTOGEN=libmkb/autogen.h libmkb/autogen.c
LIBMKB_C=libmkb/libmkb.c libmkb/op.c libmkb/vm.c libmkb/fmt.c libmkb/comp.c
LIBMKB_H=libmkb/libmkb.h libmkb/op.h libmkb/vm.h libmkb/fmt.h libmkb/comp.h

markab: markab.$O libmkb/libmkb.$O
    $LD $LDFLAGS -o markab markab.$O libmkb/libmkb.$O

mkb_test: mkb_test.$O libmkb/libmkb.$O
    $LD $LDFLAGS -o mkb_test mkb_test.$O libmkb/libmkb.$O

# The 'V:' suffix indicates a Virtual Rule. Similar to .PHONY: on POSIX make.
run:V: markab
	markab

test:V: mkb_test
	mkb_test

clean:V:
    rm -f markab mkb_test markab.$O mkb_test.$O libmkb/libmkb.$O

markab.$O: markab.c $AUTOGEN $LIBMKB_C $LIBMKB_H
    $CC $CFLAGS -DPLAN_9 markab.c

mkb_test.$O: mkb_test.c $AUTOGEN $LIBMKB_C $LIBMKB_H
    $CC $CFLAGS -DPLAN_9 mkb_test.c

libmkb/libmkb.$O: $AUTOGEN $LIBMKB_C $LIBMKB_H
    cd libmkb; $CC $CFLAGS -DPLAN_9 libmkb.c
