#!/usr/bin/python3
# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
"""
Generate NASM assembly language code for the Markab Vocab 0 dictionary (Voc0).

Struct format is:
label: dd .link                 ; link to previous list entry
       db .nameLen, <name>      ; name of word
       db .tokenLen, <tokens>   ; compiled tokens for action of word
"""

WORD_LIST = """
nop Nop
next Next
bye Bye
dup Dup
drop Drop
swap Swap
over Over
clearstack ClearStack
.s DotS
." DotQuoteI
( Paren
: Colon
emit Emit
cr CR
space Space
. Dot
+ Plus
- Minus
* Mul
/ Div
mod Mod
/mod DivMod
max Max
min Min
abs Abs
and And
or Or
xor Xor
not Not
< Less
> Greater
= Equal
0< ZeroLess
0= ZeroEqual
hex Hex
decimal Decimal
"""

ITEMS = []
SERIAL = 0
LINK = 0
LABEL = "Voc0Tail"                       # first item gets special label

lines = WORD_LIST.strip().split("\n")
for (i,line) in enumerate(lines):
  items = line.strip().split(" ")        # like CSV, but delimiter is space
  name = items[0]
  tokens = [f"{x}" for x in items[1:]]
  quote = "'" if ('"' in name) else '"'  # handle ." specially
  if i == len(lines) - 1:                # last item gets special label
    LABEL = "Voc0Head"
  indent = " " * (len(LABEL)+2)
  tokens = [f"t{x}" for x in tokens]     # transform "Foo" to "tFoo"
  fmtLink = f"{LABEL}: dd {LINK}"        # link to previous item in list
  fmtName = f"{indent}db {len(name)}, {quote}{name}{quote}"
  fmtToks = f"{indent}db {len(tokens)}, {', '.join(tokens)}"
  ITEMS += [f"{fmtLink}\n{fmtName}\n{fmtToks}\n{indent}align 16, db 0"]
  SERIAL += 1
  LINK = LABEL
  LABEL = f"Voc0_{SERIAL:03}"

COPYRIGHT = """
; Copyright (c) 2022 Sam Blenny
; SPDX-License-Identifier: MIT
;
""".strip()

CODEGEN_NOTICE = """
; ========================================================================
; === CAUTION! This file is automatically generated. Do not edit here. ===
; ========================================================================
;
; This is the data structure for the Vocab 0 dictionary linked list (Voc0)
;
""".strip()

print(COPYRIGHT)
print(CODEGEN_NOTICE)
print("align 16, db 0")
print("\n".join(ITEMS))

