#!/usr/bin/python3
# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# Generate source code for Markab VM memory map, CPU opcodes, and ECALL codes
#

MKB_OUTFILE_OP = "opcodes.mkb"
MKB_OUTFILE_MEM = "mem_map.mkb"
PY_OUTFILE_OP = "opcodes.py"
PY_OUTFILE_MEM = "mem_map.py"
PY_OUTFILE_CV = "core_voc.py"

OPCODES = """
nop NOP
+ ADD
- SUB
* MUL
& AND
~ INV
| OR
^ XOR
<< SLL
>> SRL
>>> SRA
= EQ
> GT
< LT
!= NE
0= ZE
<ASM> JMP
<ASM> JAL
; RET
<ASM> BZ
<ASM> DRBLT
r> MRT
>r MTR
rdrop RDROP
drop DROP
dup DUP
over OVER
swap SWAP
<ASM> U8
<ASM> U16
<ASM> I32
b@ LB
b! SB
h@ LH
h! SH
w@ LW
w! SW
lr LR
lpc LPC
<ASM> RESET
iod IOD
ior IOR
iodh IODH
iorh IORH
key IOKEY
emit IOEMIT
>a MTA
b@a+ LBAI
1+ INC
1- DEC
"""

MEMORY_MAP = """
0000 Boot     # Boot code (PC=0 on reset)       1 KB
03FF BootMax  # Boot code: last usable byte
0400 Heap     # Heap (dictionary)               55 KB
E000 HeapRes  # Heap Reserve buffer for WORD    256 bytes
E0FF HeapMax  # Heap: end of reserve buffer
E100 DP       # Dictionary Pointer              2 bytes (align 4)
E104 IN       # INput buffer index              1 byte  (align 4)
#...
E200 IBLen    # Input Buffer Length             1 byte
E201 IB       # Input Buffer                    255 bytes
#E2FF            end of input buffer
E300 PadLen   # Pad buffer Length               1 byte
E301 Pad      # Pad buffer                      255 bytes
#E3FF            end of pad buffer
E400 FmtLen   # Fmt buffer Length               1 byte
E401 Fmt      # Format buffer                   255 bytes
#E4FF            end of fmt buffer
#...
FFFF MemMax
"""

def filter(src):
  """Filter a comments and blank lines out of heredoc-style source string"""
  lines = src.strip().split("\n")
  lines = [L.split("#")[0].strip() for L in lines]    # filter comments
  lines = [L for L in lines if len(L) > 0]            # filter empty lines
  return lines

def mkb_opcodes():
  constants = []
  for (i, line) in enumerate(filter(OPCODES)):
    (name, opcode) = line.strip().split(" ")
    constants += [f"{i:2} const {opcode}"]
  return "\n".join(constants)

def mkb_memory_map():
  constants = []
  for line in filter(MEMORY_MAP):
    (addr, name) = line.split(" ")
    constants += [f"{addr} const {name}"]
  return "\n".join(constants)

def py_addresses():
  addrs = []
  for line in filter(MEMORY_MAP):
    (addr, name) = line.split(" ")
    addrs += [f"{name:7} = 0x{addr}"]
  return "\n".join(addrs)

def py_opcode_constants():
  ops = []
  for (i, line) in enumerate(filter(OPCODES)):
    (name, opcode) = line.strip().split(" ")
    ops += [f"{opcode.upper():6} = {i:2}"]
  return "\n".join(ops)

def py_opcode_dictionary():
  ope = []
  for (i, line) in enumerate(filter(OPCODES)):
    (name, opcode) = line.strip().split(" ")
    key = f"'{opcode.upper()}':"
    ope += [f"  {key:9} {i:>2},"]
  return "\n".join(ope)

def py_core_voc():
  cv = []
  for line in filter(MEMORY_MAP):
    (addr, name) = line.split(" ")
    key = f"'{name}':"
    cv += [f"  {key:10} (T_CONST, 0x{addr}),"]
  for (i, line) in enumerate(filter(OPCODES)):
    (name, code) = line.strip().split(" ")
    if name == '<ASM>':
      continue
    fmt_name = f"'{name}':"
    key = f"'{name}':"
    cv += [f"  {key:10} (T_OP,    {code}),"]
  return "\n".join(cv)

MKB_TEMPLATE_OP = f"""
( Copyright © 2022 Sam Blenny)
( SPDX-License-Identifier: MIT)
( === THIS FILE IS AUTOMATICALLY GENERATED ===)
( ===        DO NOT MAKE EDITS HERE        ===)
( ===      See codegen.py for details      ===)

( CPU opcodes)
{mkb_opcodes()}
""".strip()

MKB_TEMPLATE_MEM = f"""
( Copyright © 2022 Sam Blenny)
( SPDX-License-Identifier: MIT)
( === THIS FILE IS AUTOMATICALLY GENERATED ===)
( ===        DO NOT MAKE EDITS HERE        ===)
( ===      See codegen.py for details      ===)

( Memory map)
( 0000..00FF belongs to VM)
( 0100..FFFF belongs to kernel)
hex
{mkb_memory_map()}
decimal
""".strip()

PY_TEMPLATE_OP = f"""
# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details

{py_opcode_constants()}

OPCODES = {{
{py_opcode_dictionary()}
}}
""".strip()

PY_TEMPLATE_MEM = f"""
# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details

{py_addresses()}
""".strip()

PY_TEMPLATE_CV = f"""
# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details
#
from {PY_OUTFILE_OP[:-3]} import *

T_VAR   = 0
T_CONST = 1
T_OP    = 2
T_CODE  = 3

CORE_VOC = {{
{py_core_voc()}
}}
""".strip()

with open(MKB_OUTFILE_OP, 'w') as f:
  f.write(MKB_TEMPLATE_OP)
  f.write("\n")

with open(MKB_OUTFILE_MEM, 'w') as f:
  f.write(MKB_TEMPLATE_MEM)
  f.write("\n")

with open(PY_OUTFILE_OP, 'w') as f:
  f.write(PY_TEMPLATE_OP)
  f.write("\n")

with open(PY_OUTFILE_MEM, 'w') as f:
  f.write(PY_TEMPLATE_MEM)
  f.write("\n")

with open(PY_OUTFILE_CV, 'w') as f:
  f.write(PY_TEMPLATE_CV)
  f.write("\n")
