# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details
#
from opcodes import *

T_VAR   = 0
T_CONST = 1
T_OP    = 2
T_CODE  = 3

CORE_VOC = {
  'Boot':    (T_CONST, 0x0000),
  'BootMax': (T_CONST, 0x03FF),
  'Heap':    (T_CONST, 0x0400),
  'HeapRes': (T_CONST, 0xE000),
  'HeapMax': (T_CONST, 0xE0FF),
  'DP':      (T_CONST, 0xE100),
  'IN':      (T_CONST, 0xE104),
  'IBLen':   (T_CONST, 0xE200),
  'IB':      (T_CONST, 0xE201),
  'PadLen':  (T_CONST, 0xE300),
  'Pad':     (T_CONST, 0xE301),
  'FmtLen':  (T_CONST, 0xE400),
  'Fmt':     (T_CONST, 0xE401),
  'MemMax':  (T_CONST, 0xFFFF),
  'nop':     (T_OP,    NOP),
  '+':       (T_OP,    ADD),
  '-':       (T_OP,    SUB),
  '*':       (T_OP,    MUL),
  '&':       (T_OP,    AND),
  '~':       (T_OP,    INV),
  '|':       (T_OP,    OR),
  '^':       (T_OP,    XOR),
  '<<':      (T_OP,    SLL),
  '>>':      (T_OP,    SRL),
  '>>>':     (T_OP,    SRA),
  '=':       (T_OP,    EQ),
  '>':       (T_OP,    GT),
  '<':       (T_OP,    LT),
  '!=':      (T_OP,    NE),
  '0=':      (T_OP,    ZE),
  ';':       (T_OP,    RET),
  'r>':      (T_OP,    MRT),
  '>r':      (T_OP,    MTR),
  'rdrop':   (T_OP,    RDROP),
  'drop':    (T_OP,    DROP),
  'dup':     (T_OP,    DUP),
  'over':    (T_OP,    OVER),
  'swap':    (T_OP,    SWAP),
  'b@':      (T_OP,    LB),
  'b!':      (T_OP,    SB),
  'h@':      (T_OP,    LH),
  'h!':      (T_OP,    SH),
  'w@':      (T_OP,    LW),
  'w!':      (T_OP,    SW),
  'lr':      (T_OP,    LR),
  'lpc':     (T_OP,    LPC),
  'iod':     (T_OP,    IOD),
  'ior':     (T_OP,    IOR),
  'iodh':    (T_OP,    IODH),
  'iorh':    (T_OP,    IORH),
  'key':     (T_OP,    IOKEY),
  'emit':    (T_OP,    IOEMIT),
  '>a':      (T_OP,    MTA),
  'b@a+':    (T_OP,    LBAI),
  '1+':      (T_OP,    INC),
}
