( Copyright © 2022 Sam Blenny)
( SPDX-License-Identifier: MIT)
( === THIS FILE IS AUTOMATICALLY GENERATED ===)
( ===        DO NOT MAKE EDITS HERE        ===)
( ===      See codegen.py for details      ===)

( Memory map)
( 0000..00FF belongs to VM)
( 0100..FFFF belongs to kernel)
hex
0000 const IO
003F const IOEnd
0050 const A
0054 const T
0058 const R
005C const DSDeep
005D const RSDeep
005E const IP
0060 const DStack
00A0 const RStack
00E0 const Fence
0100 const Heap
CD00 const HeapRes
CFFF const HeapMax
D000 const IN
D004 const DP
D008 const IBPtr
D00C const IBLen
E000 const TIB
E3FF const TIBMax
E400 const BLK
E7FF const BLKMax
E800 const Pad
EBFF const PadMax
EC00 const Fmt
EFFF const FmtMax
FFFF const MemMax
decimal
