# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details

IO      = 0x0000
IOEnd   = 0x00FF
Boot    = 0x0100
BootMax = 0x03FF
Heap    = 0x0400
HeapRes = 0xCC00
HeapMax = 0xCFFF
DP      = 0xD000
IN      = 0xD004
IBPtr   = 0xD008
IBLen   = 0xD00C
TIB     = 0xE000
TIBMax  = 0xE3FF
BLK     = 0xE400
BLKMax  = 0xE7FF
Pad     = 0xE800
PadMax  = 0xEBFF
Fmt     = 0xEC00
FmtMax  = 0xEFFF
MemMax  = 0xFFFF
