# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details

Boot    = 0x0000
BootMax = 0x03FF
Heap    = 0x0400
HeapRes = 0xE000
HeapMax = 0xE0FF
DP      = 0xE100
IN      = 0xE104
IBLen   = 0xE200
IB      = 0xE201
PadLen  = 0xE300
Pad     = 0xE301
FmtLen  = 0xE400
Fmt     = 0xE401
MemMax  = 0xFFFF
