# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details

NOP    =  0
ADD    =  1
SUB    =  2
MUL    =  3
AND    =  4
INV    =  5
OR     =  6
XOR    =  7
SLL    =  8
SRL    =  9
SRA    = 10
EQ     = 11
GT     = 12
LT     = 13
NE     = 14
ZE     = 15
JMP    = 16
JAL    = 17
RET    = 18
BZ     = 19
DRBLT  = 20
MRT    = 21
MTR    = 22
DROP   = 23
DUP    = 24
OVER   = 25
SWAP   = 26
U8     = 27
U16    = 28
I32    = 29
LB     = 30
SB     = 31
LH     = 32
SH     = 33
LW     = 34
SW     = 35
RESET  = 36
ECALL  = 37

E_DS    =  1
E_RS    =  2
E_DSH   =  3
E_RSH   =  4
E_PC    =  5
E_READ  =  6
E_WRITE =  7
