( Copyright © 2022 Sam Blenny)
( SPDX-License-Identifier: MIT)
( === THIS FILE IS AUTOMATICALLY GENERATED ===)
( ===        DO NOT MAKE EDITS HERE        ===)
( ===      See codegen.py for details      ===)

( MarkabVM virtual CPU opcodes)
 0 const NOP
 1 const ADD
 2 const SUB
 3 const MUL
 4 const AND
 5 const INV
 6 const OR
 7 const XOR
 8 const SLL
 9 const SRL
10 const SRA
11 const EQ
12 const GT
13 const LT
14 const NE
15 const ZE
16 const JMP
17 const JAL
18 const RET
19 const BZ
20 const DRBLT
21 const MRT
22 const MTR
23 const DROP
24 const DUP
25 const OVER
26 const SWAP
27 const U8
28 const U16
29 const I32
30 const LB
31 const SB
32 const LH
33 const SH
34 const LW
35 const SW
36 const RESET
37 const ECALL

( MarkabVM environment call (syscall) constants
 1 const E_DS
 2 const E_RS
 3 const E_DSH
 4 const E_RSH
 5 const E_PC
 6 const E_READ
 7 const E_WRITE
