# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details

OPCODE_FOR_TOKEN = {
  0: 'Nop',
  1: 'And',
  2: 'BFetch',
  3: 'BStore',
  4: 'Drop',
  5: 'Dup',
  6: 'Equal',
  7: 'Fetch',
  8: 'Greater',
  9: 'Invert',
  10: 'Less',
  11: 'Minus',
  12: 'Mul',
  13: 'NotEq',
  14: 'Or',
  15: 'Over',
  16: 'Plus',
  17: 'Reset',
  18: 'RFrom',
  19: 'ShiftLeft',
  20: 'ShiftRightU32',
  21: 'ShiftRightI32',
  22: 'Store',
  23: 'Swap',
  24: 'ToR',
  25: 'WFetch',
  26: 'WStore',
  27: 'Xor',
  28: 'ZeroEq',
}

TOKEN_FOR_OPCODE = {
  'Nop': 0,
  'And': 1,
  'BFetch': 2,
  'BStore': 3,
  'Drop': 4,
  'Dup': 5,
  'Equal': 6,
  'Fetch': 7,
  'Greater': 8,
  'Invert': 9,
  'Less': 10,
  'Minus': 11,
  'Mul': 12,
  'NotEq': 13,
  'Or': 14,
  'Over': 15,
  'Plus': 16,
  'Reset': 17,
  'RFrom': 18,
  'ShiftLeft': 19,
  'ShiftRightU32': 20,
  'ShiftRightI32': 21,
  'Store': 22,
  'Swap': 23,
  'ToR': 24,
  'WFetch': 25,
  'WStore': 26,
  'Xor': 27,
  'ZeroEq': 28,
}

def get_opcode(token):
  return OPCODE_FOR_TOKEN[token]

def get_token(opcode):
  return TOKEN_FOR_OPCODE[opcode]
