# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details

OPCODE_FOR_TOKEN = {
  0: 'Nop',
  1: 'Add',
  2: 'Sub',
  3: 'Mul',
  4: 'And',
  5: 'Inv',
  6: 'Or',
  7: 'Xor',
  8: 'ShL',
  9: 'ShR',
  10: 'ShA',
  11: 'Eq',
  12: 'GT',
  13: 'LT',
  14: 'NE',
  15: 'ZE',
  16: 'Jmp',
  17: 'Call',
  18: 'Ret',
  19: 'RFrom',
  20: 'ToR',
  21: 'Reset',
  22: 'Drop',
  23: 'Dup',
  24: 'Over',
  25: 'Swap',
  26: 'U8',
  27: 'U16',
  28: 'I32',
  29: 'BFetch',
  30: 'BStore',
  31: 'WFetch',
  32: 'WStore',
  33: 'Fetch',
  34: 'Store',
}

TOKEN_FOR_OPCODE = {
  'Nop': 0,
  'Add': 1,
  'Sub': 2,
  'Mul': 3,
  'And': 4,
  'Inv': 5,
  'Or': 6,
  'Xor': 7,
  'ShL': 8,
  'ShR': 9,
  'ShA': 10,
  'Eq': 11,
  'GT': 12,
  'LT': 13,
  'NE': 14,
  'ZE': 15,
  'Jmp': 16,
  'Call': 17,
  'Ret': 18,
  'RFrom': 19,
  'ToR': 20,
  'Reset': 21,
  'Drop': 22,
  'Dup': 23,
  'Over': 24,
  'Swap': 25,
  'U8': 26,
  'U16': 27,
  'I32': 28,
  'BFetch': 29,
  'BStore': 30,
  'WFetch': 31,
  'WStore': 32,
  'Fetch': 33,
  'Store': 34,
}

NOP    =  0
ADD    =  1
SUB    =  2
MUL    =  3
AND    =  4
INV    =  5
OR     =  6
XOR    =  7
SHL    =  8
SHR    =  9
SHA    = 10
EQ     = 11
GT     = 12
LT     = 13
NE     = 14
ZE     = 15
JMP    = 16
CALL   = 17
RET    = 18
RFROM  = 19
TOR    = 20
RESET  = 21
DROP   = 22
DUP    = 23
OVER   = 24
SWAP   = 25
U8     = 26
U16    = 27
I32    = 28
BFETCH = 29
BSTORE = 30
WFETCH = 31
WSTORE = 32
FETCH  = 33
STORE  = 34

def get_opcode(token):
  return OPCODE_FOR_TOKEN[token]

def get_token(opcode):
  return TOKEN_FOR_OPCODE[opcode]
