# Copyright (c) 2022 Sam Blenny
# SPDX-License-Identifier: MIT
#
# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT MAKE EDITS HERE
# See codegen.py for details

OPCODE_FOR_TOKEN = {
  0: 'Nop',
  1: 'And',
  2: 'BFetch',
  3: 'BStore',
  4: 'Call',
  5: 'Drop',
  6: 'Dup',
  7: 'Equal',
  8: 'Fetch',
  9: 'Greater',
  10: 'Invert',
  11: 'Jump',
  12: 'Less',
  13: 'Lit16',
  14: 'Lit32',
  15: 'Lit8',
  16: 'Minus',
  17: 'Mul',
  18: 'NotEq',
  19: 'Or',
  20: 'Over',
  21: 'Plus',
  22: 'Reset',
  23: 'Return',
  24: 'RFrom',
  25: 'ShiftLeft',
  26: 'ShiftRightU32',
  27: 'ShiftRightI32',
  28: 'Store',
  29: 'Swap',
  30: 'ToR',
  31: 'WFetch',
  32: 'WStore',
  33: 'Xor',
  34: 'ZeroEq',
}

TOKEN_FOR_OPCODE = {
  'Nop': 0,
  'And': 1,
  'BFetch': 2,
  'BStore': 3,
  'Call': 4,
  'Drop': 5,
  'Dup': 6,
  'Equal': 7,
  'Fetch': 8,
  'Greater': 9,
  'Invert': 10,
  'Jump': 11,
  'Less': 12,
  'Lit16': 13,
  'Lit32': 14,
  'Lit8': 15,
  'Minus': 16,
  'Mul': 17,
  'NotEq': 18,
  'Or': 19,
  'Over': 20,
  'Plus': 21,
  'Reset': 22,
  'Return': 23,
  'RFrom': 24,
  'ShiftLeft': 25,
  'ShiftRightU32': 26,
  'ShiftRightI32': 27,
  'Store': 28,
  'Swap': 29,
  'ToR': 30,
  'WFetch': 31,
  'WStore': 32,
  'Xor': 33,
  'ZeroEq': 34,
}

def get_opcode(token):
  return OPCODE_FOR_TOKEN[token]

def get_token(opcode):
  return TOKEN_FOR_OPCODE[opcode]
