( Copyright © 2022 Sam Blenny)
( SPDX-License-Identifier: MIT)
( === THIS FILE IS AUTOMATICALLY GENERATED ===)
( ===        DO NOT MAKE EDITS HERE        ===)
( ===      See codegen.py for details      ===)

( MarkabVM virtual CPU opcode tokens)
 0 const Nop
 1 const Add
 2 const Sub
 3 const Mul
 4 const And
 5 const Inv
 6 const Or
 7 const Xor
 8 const ShL
 9 const ShR
10 const ShA
11 const Eq
12 const GT
13 const LT
14 const NE
15 const ZE
16 const Call
17 const Jmp
18 const Ret
19 const RFrom
20 const ToR
21 const Reset
22 const Drop
23 const Dup
24 const Over
25 const Swap
26 const U8
27 const U16
28 const I32
29 const BFetch
30 const BStore
31 const WFetch
32 const WStore
33 const Fetch
34 const Store

( MarkabForth core vocabulary)
: nop   tok> Nop ;
: +     tok> Add ;
: -     tok> Sub ;
: *     tok> Mul ;
: &     tok> And ;
: ~     tok> Inv ;
: |     tok> Or ;
: ^     tok> Xor ;
: <<    tok> ShL ;
: >>    tok> ShR ;
: >>>   tok> ShA ;
: =     tok> Eq ;
: >     tok> GT ;
: <     tok> LT ;
: <>    tok> NE ;
: 0=    tok> ZE ;
: ;     tok> Ret ;
: r>    tok> RFrom ;
: >r    tok> ToR ;
: reset tok> Reset ;
: drop  tok> Drop ;
: dup   tok> Dup ;
: over  tok> Over ;
: swap  tok> Swap ;
: b@    tok> BFetch ;
: b!    tok> BStore ;
: w@    tok> WFetch ;
: w!    tok> WStore ;
: @     tok> Fetch ;
: !     tok> Store ;
