( Copyright © 2022 Sam Blenny)
( SPDX-License-Identifier: MIT)
( === THIS FILE IS AUTOMATICALLY GENERATED ===)
( ===        DO NOT MAKE EDITS HERE        ===)
( ===      See codegen.py for details      ===)

( MarkabVM virtual CPU opcode tokens)
 0 const Nop
 1 const And
 2 const BFetch
 3 const BStore
 4 const DivMod
 5 const Drop
 6 const Dup
 7 const Equal
 8 const Fetch
 9 const Greater
10 const Invert
11 const IOFetch
12 const IOStore
13 const Less
14 const Minus
15 const Mul
16 const NotEq
17 const Or
18 const Over
19 const Plus
20 const Reset
21 const RFrom
22 const Store
23 const Swap
24 const ToR
25 const WFetch
26 const WStore
27 const Xor
28 const ZeroEq

( MarkabForth core vocabulary)
: nop   tok> Nop ;
: &     tok> And ;
: b@    tok> BFetch ;
: b!    tok> BStore ;
: /%    tok> DivMod ;
: drop  tok> Drop ;
: dup   tok> Dup ;
: =     tok> Equal ;
: @     tok> Fetch ;
: >     tok> Greater ;
: ~     tok> Invert ;
: io@   tok> IOFetch ;
: io!   tok> IOStore ;
: <     tok> Less ;
: -     tok> Minus ;
: *     tok> Mul ;
: <>    tok> NotEq ;
: |     tok> Or ;
: over  tok> Over ;
: +     tok> Plus ;
: reset tok> Reset ;
: r>    tok> RFrom ;
: !     tok> Store ;
: swap  tok> Swap ;
: >r    tok> ToR ;
: w@    tok> WFetch ;
: w!    tok> WStore ;
: ^     tok> Xor ;
: 0=    tok> ZeroEq ;
