( Copyright © 2022 Sam Blenny)
( SPDX-License-Identifier: MIT)
( === THIS FILE IS AUTOMATICALLY GENERATED ===)
( ===        DO NOT MAKE EDITS HERE        ===)
( ===      See codegen.py for details      ===)

( MarkabVM virtual CPU opcode tokens)
 0 const Nop
 1 const And
 2 const BFetch
 3 const BStore
 4 const Drop
 5 const Dup
 6 const Equal
 7 const Fetch
 8 const Greater
 9 const Invert
10 const IOFetch
11 const IOStore
12 const Less
13 const Minus
14 const Mul
15 const NotEq
16 const Or
17 const Over
18 const Plus
19 const Reset
20 const RFrom
21 const ShiftLeft
22 const ShiftRightU32
23 const ShiftRightI32
24 const Store
25 const Swap
26 const ToR
27 const WFetch
28 const WStore
29 const Xor
30 const ZeroEq

( MarkabForth core vocabulary)
: nop   tok> Nop ;
: &     tok> And ;
: b@    tok> BFetch ;
: b!    tok> BStore ;
: drop  tok> Drop ;
: dup   tok> Dup ;
: =     tok> Equal ;
: @     tok> Fetch ;
: >     tok> Greater ;
: ~     tok> Invert ;
: io@   tok> IOFetch ;
: io!   tok> IOStore ;
: <     tok> Less ;
: -     tok> Minus ;
: *     tok> Mul ;
: <>    tok> NotEq ;
: |     tok> Or ;
: over  tok> Over ;
: +     tok> Plus ;
: reset tok> Reset ;
: r>    tok> RFrom ;
: <<    tok> ShiftLeft ;
: >>    tok> ShiftRightU32 ;
: >>>   tok> ShiftRightI32 ;
: !     tok> Store ;
: swap  tok> Swap ;
: >r    tok> ToR ;
: w@    tok> WFetch ;
: w!    tok> WStore ;
: ^     tok> Xor ;
: 0=    tok> ZeroEq ;
